FROM ubuntu:latest

RUN apt-get update
RUN apt-get install build-essential -y
RUN apt-get install wget -y
RUN apt-get install -y iputils-ping net-tools
RUN apt-get install -y iproute2 -y
RUN apt-get install -y iperf3
RUN apt-get install iptables -y
RUN apt-get install bridge-utils
RUN apt-get install traceroute
RUN ["apt-get", "install", "-y", "vim"]
RUN apt-get install systemctl -y
RUN apt-get install tcpdump -y
